name: Sugerir una mejora
description: Una idea o algo que te gustaría que WaveType hiciera.
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: Tu idea
      description: Qué te gustaría y para qué te serviría.
    validations:
      required: true
